### PR TITLE
Add DeepMET model files

### PR DESCRIPTION
**Pull request by steggema**
This adds 5 model files for DeepMET:
2018 training, both regular and response-corrected;
2016 training, only response-corrected;
and phase 2 training, both regular and response-corrected.

The concurrent cms-sw PR is here https://github.com/cms-sw/cmssw/pull/29764

@intrepid42 @yongbinfeng

### CODE REVIEW

**Comment by slava77** [comment]
@steggema 
please add a README.md or txt in the deepmet subdirectory to briefly describe the files.

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#29764

**Comment by slava77** [comment]
+1

based on cms-sw/cmssw#29764

**Comment by smuzaffar** [comment]
+externals
only new files, so can be merged and integrated in next IB

**Pull request merged**
