### PR TITLE
Adding DeepMET files in structure needed for SONIC

### PR DESCRIPTION
**Pull request by wpmccormack**
This is a companion PR to https://github.com/cms-sw/cmssw/pull/37963.  We are adding a SONIC producer for DeepMET to CMSSW to do some production tests.   Nominally SONIC is designed to enable easy use of co-processors in CMS workflows, but it can also start up CPU-based inference servers within jobs.  This PR does not affect any workflow in CMS in any way unless called specifically (the SONIC producer is independent of the general DeepMET one).  The SONIC framework requires the model files and a specifically formatted config file for the Triton server, and these are contained in this PR in the structure required by NVIDIA Triton.  Please refer to these slides for more information about SONIC and our use of NVIDIA Triton: https://indico.cern.ch/event/1143469/contributions/4799423/attachments/2416540/4135308/March_28_JetMET_SONIC.pdf

### CODE REVIEW

**Comment by kpedro88** [comment]
The folder `RecoMET-METPUSubtraction/deepmet` has files in it that are not Triton-related. This can cause issues in the Triton server, though it seems to be working in this particular case. It would be better to have a folder structure `models/deepmet`, with that folder containing only the `config.pbtxt` and model files.

Also, we had previously discussed with @cms-sw/jetmet-pog-l2 the possibility of relocating the model files rather than copying them. It would be good to pursue this if possible.

**Comment by wpmccormack** [comment]
Ah, ok I can move them from deepmet/deepmet to something like models/deepmet.  Do you know where the model files originally are, or should I contact the JetMET people?  Or I guess model 1 is equivalent to deepmet_v1_phase2.pb and model 2 is equivalent to deepmet_resp_v1_phase2.pb

**Comment by kpedro88** [comment]
please use `deepmet_v1_2018/model.graphdef` rather than `1/model.graphdef` (etc.) for clarity

**Comment by wpmccormack** [comment]
I think Triton requires that the model version has to be an integer

**Comment by kpedro88** [comment]
To get around this, I'm now envisioning something like `autoCond`: a dictionary mapping descriptive names to folder version numbers. There could be one of these per algorithm, with the readme here pointing to the CMSSW python file that contains the dictionary. This would make the CMSSW configs more expressive, while still avoiding duplication of model files in cms-data. Probably merits some discussion with ML and JME.

**Comment by wpmccormack** [comment]
Ah ok cool, I'll send an email (but probably not right now, since people probably wouldn't see it until next week anyways)

**Comment by kpedro88** [comment]
@wpmccormack you have to do this for every version, not just 1 and 2, i.e. assign numbers to each of the other versions. otherwise, the other workflows in the PR tests will not work.

**Comment by wpmccormack** [comment]
Oh, why is that?  The other versions are not symbolic links.  I can make them links easily of course, but will we be using sonic for the other versions?

**Comment by kpedro88** [comment]
Workflows using SONIC for Run 3 and Phase 2 exist (and are being executed in the tests of https://github.com/cms-sw/cmssw/pull/37963), so either we have to support them or remove them. I think we should try to be comprehensive.

**Comment by wpmccormack** [comment]
Ah gotcha.  I'll give them numbers and re-push

**Comment by kpedro88** [comment]
@wpmccormack I think a mistake was made with the phase2 models. The file sizes are not the same as what's in the upstream. Can you go back to upstream and copy the files to ensure the correct ones are used?

**Comment by wpmccormack** [comment]
Yikes, yes, somehow I had copied the files into their new folders incorrectly.  I've gone back in and double checked that they're right in the most recent push now

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/37963#issuecomment-1144363195
- moves the DeepMET models to comply with Triton requirements
- does not change standard reco outputs

**Comment by jpata** [comment]
I think the test here fails because it needs to be tested together with https://github.com/cms-sw/cmssw/pull/37963.

**Comment by perrotta** [comment]
+1
- Tested together with https://github.com/cms-sw/cmssw/pull/37963

**Comment by perrotta** [comment]
merge

**Pull request merged**
